export const ogStyles = [
  {
    name: "A Scottish Landscape",
    by: "Alistair Shepherd",
    id: "a-scottish-landscape",
    twitterHandle: "accudio",
    twitterUrl: "https://twitter.com/accudio",
    websiteHandle: "AlistairShepherd.uk",
    websiteUrl: "https://alistairshepherd.uk/",
  },
  {
    name: "Abandoned Stage",
    by: "Andrey Kudryavtsev",
    id: "abandoned-stage",
    twitterHandle: "cat__logic",
    twitterUrl: "https://twitter.com/cat__logic",
    websiteHandle: "catlogic.ru",
    websiteUrl: "https://catlogic.ru/",
  },
  {
    name: "AeroJet-505",
    by: "Charles Henri",
    id: "aerojet-505",
  },
  {
    name: "Animado",
    by: "Elisangela Silva",
    id: "animado",
    twitterHandle: "elisannsilva",
    twitterUrl: "https://twitter.com/elisannsilva",
  },
  {
    name: "Artsy Blue and Turquoise",
    by: "Thea Kitzinger",
    id: "artsy-blue-and-turquoise",
    websiteHandle: "theakitzinger.netlify.com",
    websiteUrl: "https://theakitzinger.netlify.com/",
  },
  {
    name: "At The Desk",
    by: "Tamás Tömördi",
    id: "at-the-desk",
    websiteHandle: "tomordi.com",
    websiteUrl: "https://tomordi.com/",
  },
  {
    name: "Atomic Clock",
    by: "Eric Brown",
    id: "atomic-clock",
  },
  {
    name: "Barebones",
    by: "Vinícius Philot",
    id: "barebones",
    twitterHandle: "vphilot",
    twitterUrl: "https://twitter.com/vphilot",
    websiteHandle: "philot.ca",
    websiteUrl: "https://philot.ca/",
  },
  {
    name: "Blue-Beast",
    by: "Kiran Shrinivaas S",
    id: "blue-beast",
  },
  {
    name: "Blueprint",
    by: "Todd Libby",
    id: "blueprint",
    twitterHandle: "toddlibby",
    twitterUrl: "https://twitter.com/toddlibby",
    websiteHandle: "toddl.dev",
    websiteUrl: "https://toddl.dev/",
  },
  {
    name: "Borlandish",
    by: "Vishwa.R",
    id: "borlandish",
    websiteHandle: "Vishwa.R | Portfolio",
    websiteUrl: "https://code-reaper08.github.io/Vishwa/",
  },
  {
    name: "Boysenberry",
    by: "Evan Thome",
    id: "boysenberry",
  },
  {
    name: "Bulletin",
    by: "Paulo Nunes",
    id: "bulletin",
  },
  {
    name: "Calm",
    by: "Tripti Nayak",
    id: "calm",
  },
  {
    name: "Center Stage",
    by: "Katie Langerman",
    id: "center-stage",
    twitterHandle: "Katielangerman",
    twitterUrl: "https://twitter.com/Katielangerman",
    websiteHandle: "langermank.com",
    websiteUrl: "https://www.langermank.com/",
  },
  {
    name: "Color Stages",
    by: "Claire Lipskey",
    id: "color-stages",
    twitterHandle: "tackjhompson",
    twitterUrl: "https://twitter.com/tackjhompson",
    websiteHandle: "lipskey.me",
    websiteUrl: "http://lipskey.me/",
  },
  {
    name: "Colorful Cards",
    by: "Inklingboi",
    id: "colorful-cards",
    websiteHandle: "Arcade Archive",
    websiteUrl: "https://arcade-archive-next.vercel.app/",
  },
  {
    name: "Comic",
    by: "Katherine Kato",
    id: "comic",
    twitterHandle: "kato_katherine",
    twitterUrl: "https://twitter.com/kato_katherine",
    websiteHandle: "katherinekato.com",
    websiteUrl: "https://katherinekato.com/",
  },
  {
    name: "Crawling Chaos",
    by: "Adrian Bece",
    id: "crawling-chaos",
    twitterHandle: "AdrianBeceDev",
    twitterUrl: "https://twitter.com/AdrianBeceDev",
    websiteHandle: "codeAdrian",
    websiteUrl: "https://codeadrian.github.io/",
  },
  {
    name: "CSS CLI",
    by: "Ryan Mulligan",
    id: "css-cli",
    twitterHandle: "hexagoncircle",
    twitterUrl: "https://twitter.com/hexagoncircle",
    websiteHandle: "hexagoncircle.com",
    websiteUrl: "https://hexagoncircle.com/",
  },
  {
    name: "Dark- Navy & Green",
    by: "Vishal Sharma",
    id: "dark-navy-and-green",
    twitterHandle: "iamvishal345",
    twitterUrl: "https://twitter.com/iamvishal345",
    websiteHandle: "CodeEntity.tech",
    websiteUrl: "https://www.codeentity.tech/",
  },
  {
    name: "Dark-Purple",
    by: "Jayashakthi Vishnu P",
    id: "dark-purple",
  },
  {
    name: "Darkified",
    by: "Arul Murugavel",
    id: "darkified",
  },
  {
    name: "DeSoto",
    by: "Joey Imlay",
    id: "desoto",
    twitterHandle: "dentednerd",
    twitterUrl: "https://twitter.com/dentednerd",
    websiteHandle: "joeyimlay.dev",
    websiteUrl: "https://joeyimlay.dev/",
  },
  {
    name: "Drafter",
    by: "Claudine Ong",
    id: "drafter",
    twitterHandle: "msclaudo",
    twitterUrl: "https://twitter.com/msclaudo",
    websiteHandle: "claudine.onglab.com",
    websiteUrl: "https://claudine.onglab.com/",
  },
  {
    name: "Drawing Board",
    by: "Emma Grey",
    id: "drawing-board",
    twitterHandle: "greyypse",
    twitterUrl: "https://twitter.com/greyypse",
  },
  {
    name: "Eighties Synthwave",
    by: "Kevin Powell",
    id: "eighties-synthwave",
    twitterHandle: "KevinJPowell",
    twitterUrl: "https://twitter.com/KevinJPowell",
    websiteHandle: "kevinpowell.co",
    websiteUrl: "https://kevinpowell.co/",
  },
  {
    name: "Emphasis",
    by: "d-cs",
    id: "emphasis",
    twitterHandle: "_dcsutton",
    twitterUrl: "https://twitter.com/_dcsutton",
  },
  {
    name: "Final Frontier",
    by: "Danielle Mayabb",
    id: "final-frontier",
    twitterHandle: "thescifibrarian",
    twitterUrl: "https://twitter.com/thescifibrarian",
    websiteHandle: "danielle-m.dev",
    websiteUrl: "https://danielle-m.dev/",
  },
  {
    name: "Floral vibes",
    by: "Neelam Chavan",
    id: "floral-vibes",
    websiteHandle: "Neelam C Linkedin",
    websiteUrl: "https://www.linkedin.com/in/neelam-chavan-3110141b7/",
  },
  {
    name: "Fresh",
    by: "Thomas Champion",
    id: "fresh",
    websiteHandle: "Thomas Champion",
    websiteUrl: "http://thomaschampion.info/",
  },
  {
    name: "Gallery",
    by: "Olivia Ng",
    id: "gallery",
    twitterHandle: "meowlivia_",
    twitterUrl: "https://twitter.com/meowlivia_",
  },
  {
    name: "Geocities",
    by: "whitep4nth3r",
    id: "geocities",
    twitterHandle: "whitep4nth3r",
    twitterUrl: "https://twitter.com/whitep4nth3r",
    websiteHandle: "whitep4nth3r.com",
    websiteUrl: "https://whitep4nth3r.com/",
  },
  {
    name: "Hackytoberfest",
    by: "Jordana Harrison",
    id: "hackytoberfest",
    twitterHandle: "JordanaBananza",
    twitterUrl: "https://twitter.com/JordanaBananza",
    websiteHandle: "Jordana's Site",
    websiteUrl: "https://jordanaharrison.com/",
  },
  {
    name: "Happy Halloween",
    by: "Fredorixo",
    id: "happy-halloween",
  },
  {
    name: "Headquarters",
    by: "Stephanie Eckles",
    id: "headquarters",
    twitterHandle: "5t3ph",
    twitterUrl: "https://twitter.com/5t3ph",
    websiteHandle: "ModernCSS.dev",
    websiteUrl: "https://moderncss.dev/",
  },
  {
    name: "I Got The Blues",
    by: "Jessica Nagar",
    id: "i-got-the-blues",
  },
  {
    name: "iStage",
    by: "Bahe Yaich",
    id: "istage",
    twitterHandle: "notBahe",
    twitterUrl: "https://twitter.com/notBahe",
  },
  {
    name: "Jet Set",
    by: "Cory Birdsong",
    id: "jet-set",
    twitterHandle: "cbirdsong",
    twitterUrl: "https://twitter.com/cbirdsong",
    websiteHandle: "birdsong.dev",
    websiteUrl: "https://birdsong.dev/",
  },
  {
    name: "Liquid Style",
    by: "Toni Rome",
    id: "liquid-style",
    websiteHandle: "guyrome.com",
    websiteUrl: "https://guyrome.com/",
  },
  {
    name: "Web 2.0 Lobster Party",
    by: "Andy Bell",
    id: "web-2.0-lobster-party",
    twitterHandle: "hankchizljaw",
    twitterUrl: "https://twitter.com/hankchizljaw",
    websiteHandle: "Piccalilli",
    websiteUrl: "https://piccalil.li/",
  },
  {
    name: "Manual",
    by: "Lynn Fisher",
    id: "manual",
    twitterHandle: "lynnandtonic",
    twitterUrl: "https://twitter.com/lynnandtonic",
    websiteHandle: "lynnandtonic.com",
    websiteUrl: "https://lynnandtonic.com/",
  },
  {
    name: "Mburucuya",
    by: "Lide O.",
    id: "mburucuya",
    websiteHandle: "lideo.dev",
    websiteUrl: "https://lideo.dev/",
  },
  {
    name: "Moccasin Stage",
    by: "Gabriel Paixao",
    id: "moccasin-stage",
  },
  {
    name: "Modern stars",
    by: "Alba Maldonado",
    id: "modern-stars",
  },
  {
    name: "MonoMinimal",
    by: "Amit Sheen",
    id: "monominimal",
    twitterHandle: "amit_sheen",
    twitterUrl: "https://twitter.com/amit_sheen",
    websiteHandle: "amitsh.com",
    websiteUrl: "https://amitsh.com/site/",
  },
  {
    name: "Neomorphism Design",
    by: "Manoranjan D",
    id: "neomorphism-design",
  },
  {
    name: "Neon Beetles",
    by: "Barbara Aliverti",
    id: "neon-beetles",
    twitterHandle: "baloobali_",
    twitterUrl: "https://twitter.com/baloobali_",
    websiteHandle: "Find me on GitHub",
    websiteUrl: "https://github.com/barbaraaliverti",
  },
  {
    name: "Neon",
    by: "Pablo Jimenez",
    id: "neon",
  },
  {
    name: "Nightshade",
    by: "Peter Byfield",
    id: "nightshade",
  },
  {
    name: "Pastels & Columns",
    by: "Carol McKay",
    id: "pastels-and-columns",
    twitterHandle: "carolmckayau",
    twitterUrl: "https://twitter.com/carolmckayau",
    websiteHandle: "WebAware",
    websiteUrl: "https://webaware.com.au/",
  },
  {
    name: "Pilgrim",
    by: "Gonçalo Morais",
    id: "pilgrim",
    twitterHandle: "gnclmorais",
    twitterUrl: "https://twitter.com/gnclmorais",
    websiteHandle: "gnclmorais.com",
    websiteUrl: "https://blog.gnclmorais.com/",
  },
  {
    name: "Pink Lime",
    by: "Michelle Barker",
    id: "pink-lime",
    twitterHandle: "MicheBarks",
    twitterUrl: "https://twitter.com/MicheBarks",
    websiteHandle: "CSS { In Real Life }",
    websiteUrl: "https://css-irl.info/",
  },
  {
    name: "Pink Outside The Box",
    by: "GabbyKC",
    id: "pink-outside-the-box",
    websiteHandle: "GabbyKC.github.io",
    websiteUrl: "https://gabbykc.github.io/",
  },
  {
    name: "Pipboy",
    by: "Carter Lovelace",
    id: "pipboy",
    twitterHandle: "carterfromsl",
    twitterUrl: "https://twitter.com/carterfromsl",
    websiteHandle: "stratlab.ca",
    websiteUrl: "https://stratlab.ca/",
  },
  {
    name: "Plain'n'simple",
    by: "Silvestar Bistrović",
    id: "plainnsimple",
    twitterHandle: "malimirkeccita",
    twitterUrl: "https://twitter.com/malimirkeccita",
    websiteHandle: "silvestar.codes",
    websiteUrl: "https://www.silvestar.codes/",
  },
  {
    name: "Plants on Pink",
    by: "Nicole Ortiz",
    id: "plants-on-pink",
  },
  {
    name: "Propaganda",
    by: "Maryam Hanafiah",
    id: "propaganda",
    twitterHandle: "h3110p4nd4",
    twitterUrl: "https://twitter.com/h3110p4nd4",
    websiteHandle: "pandashop",
    websiteUrl: "https://pandashop.co.uk/",
  },
  {
    name: "Purpleland",
    by: "Dawntraoz",
    id: "purpleland",
    twitterHandle: "dawntraoz",
    twitterUrl: "https://twitter.com/dawntraoz",
    websiteHandle: "Dawntraoz",
    websiteUrl: "https://dawntraoz.com/",
  },
  {
    name: "Purplify & Pastel",
    by: "Dominic Duffin",
    id: "purplify-and-pastel",
    twitterHandle: "DominicDuffin1",
    twitterUrl: "https://twitter.com/DominicDuffin1",
  },
  {
    name: "Queer Modes",
    by: "Miriam Suzanne",
    id: "queer-modes",
    twitterHandle: "MiriSuzanne",
    twitterUrl: "https://twitter.com/MiriSuzanne",
    websiteHandle: "miriamsuzanne.com",
    websiteUrl: "https://www.miriamsuzanne.com/",
  },
  {
    name: "Rainbow",
    by: "Nic Mayer",
    id: "rainbow",
    twitterHandle: "nicm4242",
    twitterUrl: "https://twitter.com/nicm4242",
    websiteHandle: "Nic",
    websiteUrl: "https://nicm42.github.io/",
  },
  {
    name: "Red Sand",
    by: "UsrnGamesInc",
    id: "red-sand",
  },
  {
    name: "Retro Cyberpunk",
    by: "Inès K.",
    id: "retro-cyberpunk",
    twitterHandle: "inescodes",
    twitterUrl: "https://twitter.com/inescodes",
  },
  {
    name: "Retro Modern",
    by: "Mike Aparicio",
    id: "retro-modern",
    twitterHandle: "peruvianidol",
    twitterUrl: "https://twitter.com/peruvianidol",
    websiteHandle: "mikeaparicio.com",
    websiteUrl: "https://mikeaparicio.com/",
  },
  {
    name: "Retro",
    by: "Rachel B",
    id: "retro",
    twitterHandle: "smolcodes",
    twitterUrl: "https://twitter.com/smolcodes",
  },
  {
    name: "Retroish",
    by: "Jean Louise Tiston",
    id: "retroish",
    twitterHandle: "jeanlouisedev",
    twitterUrl: "https://twitter.com/jeanlouisedev",
    websiteHandle: "Jean Louise Co",
    websiteUrl: "http://jeanlouise.co/",
  },
  {
    name: "Russian Inspiration",
    by: "CandiceCz",
    id: "russian-inspiration",
    websiteHandle: "Portfolio",
    websiteUrl: "https://candiceczech.com/",
  },
  {
    name: "Seifuku",
    by: "Peter Ho",
    id: "seifuku",
    websiteHandle: "Peter Ho's Homepage",
    websiteUrl: "https://peterhohk.github.io/",
  },
  {
    name: "Severe with Rainbow",
    by: "Lizard Morrow",
    id: "severe-with-rainbow",
    twitterHandle: "onlyasmallliza1",
    twitterUrl: "https://twitter.com/onlyasmallliza1",
    websiteHandle: "",
    websiteUrl: "https://onlyasmalllizard.github.io/",
  },
  {
    name: "Shadows",
    by: "Nadia Laasri",
    id: "shadows",
    twitterHandle: "laasrinadiaa",
    twitterUrl: "https://twitter.com/laasrinadiaa",
    websiteHandle: "nadialaasri.me",
    websiteUrl: "https://nadialaasri.me/",
  },
  {
    name: "Shimmering Stars",
    by: "Paola Ayala Zelaya",
    id: "shimmering-stars",
  },
  {
    name: "Simple Blue Roboto",
    by: "JCarlosR",
    id: "simple-blue-roboto",
    websiteHandle: "programacionYmas.com",
    websiteUrl: "https://programacionymas.com/",
  },
  {
    name: "Skewten",
    by: "Donnie D'Amato",
    id: "skewten",
    twitterHandle: "donniedamato",
    twitterUrl: "https://twitter.com/donniedamato",
    websiteHandle: "Donnie D'Amato",
    websiteUrl: "https://donniedamato.info/",
  },
  {
    name: "Slide Stage",
    by: "Thomas Tuvignon",
    id: "slide-stage",
    twitterHandle: "tomtuv",
    twitterUrl: "https://twitter.com/tomtuv",
    websiteHandle: "thomastuvignon.com",
    websiteUrl: "https://thomastuvignon.com/en/",
  },
  {
    name: "Soff",
    by: "Beatrice Bock",
    id: "soff",
    twitterHandle: "techwithtris",
    twitterUrl: "https://twitter.com/techwithtris",
    websiteHandle: "TechWithTris",
    websiteUrl: "https://techwithtris.com/",
  },
  {
    name: "SolidState",
    by: "Maheshkumar",
    id: "solidstate",
  },
  {
    name: "Spectrum",
    by: "Robert Manders",
    id: "spectrum",
    websiteHandle: "github.com/Rob-Manders",
    websiteUrl: "https://github.com/Rob-Manders",
  },
  {
    name: "StageOS",
    by: "Håvard Brynjulfsen",
    id: "stageos",
    twitterHandle: "brynjulfs1",
    twitterUrl: "https://twitter.com/brynjulfs1",
    websiteHandle: "havardbrynjulfsen.design",
    websiteUrl: "https://havardbrynjulfsen.design/",
  },
  {
    name: "Stageflix",
    by: "Suckcoder",
    id: "stageflix",
  },
  {
    name: "The Styles Must Go On!",
    by: "Joe Lamyman",
    id: "the-styles-must-go-on",
    twitterHandle: "JoeLamyman",
    twitterUrl: "https://twitter.com/JoeLamyman",
    websiteHandle: "Joe Lamyman's Portfolio",
    websiteUrl: "https://joelamyman.co.uk/",
  },
  {
    name: "Sweet N Sp00ky",
    by: "Aiden Schrock",
    id: "sweet-n-sp00ky",
    twitterHandle: "AidenNSchrock",
    twitterUrl: "https://twitter.com/AidenNSchrock",
    websiteHandle: "Aiden's Portfolio",
    websiteUrl: "https://stylestage.dev/styles/aidenschrock.me",
  },
  {
    name: "Sysfonts",
    by: "Halvor William Sanden",
    id: "sysfonts",
    twitterHandle: "8yard",
    twitterUrl: "https://twitter.com/8yard",
    websiteHandle: "8yd.no",
    websiteUrl: "https://8yd.no/",
  },
  {
    name: "Trafalgar",
    by: "Mike Andrewartha",
    id: "trafalgar",
    twitterHandle: "mandrewnz",
    twitterUrl: "https://twitter.com/mandrewnz",
    websiteHandle: "Mike Andrewartha",
    websiteUrl: "https://mike.andrewartha.co.nz/",
  },
  {
    name: "Transparency",
    by: "Jens Oliver Meiert",
    id: "transparency",
    twitterHandle: "j9t",
    twitterUrl: "https://twitter.com/j9t",
    websiteHandle: "meiert.com",
    websiteUrl: "https://meiert.com/en/",
  },
  {
    name: "Vaporwave",
    by: "Shannon Crabill",
    id: "vaporwave",
    twitterHandle: "shannon_crabill",
    twitterUrl: "https://twitter.com/shannon_crabill",
    websiteHandle: "shannoncrabill.com",
    websiteUrl: "http://shannoncrabill.com/",
  },
  {
    name: "Vibrant",
    by: "Lakshmikant.K",
    id: "vibrant",
    websiteHandle: "Lakshmikant.K | Portfolio",
    websiteUrl: "https://fcc-web.netlify.app/personal-portfolio",
  },
  {
    name: "We Love Teal",
    by: "Olivia Johnson",
    id: "we-love-teal",
  },
  {
    name: "Ye Olde Book",
    by: "Max Spuling",
    id: "ye-olde-book",
    twitterHandle: "TillyWater",
    twitterUrl: "https://twitter.com/TillyWater",
    websiteHandle: "max_spuling",
    websiteUrl: "https://maxspuling.de/",
  },
  {
    name: "Yellowed",
    by: "Sowmya Seshadri",
    id: "yellowed",
    twitterHandle: "seshadrisowmya",
    twitterUrl: "https://twitter.com/seshadrisowmya",
  },
];

export const defaultStyle = ogStyles.find((s) => s.id === "bulletin")!;
